name: Run Python Unit Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [self-hosted, ubuntu-latest, windows-latest, macos-13]
        python-version: ['3.10']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update setuptools
      run: |
        pip install --upgrade pip
        pip install setuptools==78.1.1 wheel==0.45.1

    - name: Install dependencies
      run: |
        pip install -q -e ".[dev]"
        pip install pytest coverage

    - name: Run tests with coverage
      run: |
        pytest --cov=agentscope_runtime tests/

    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}